config/routes.rb
Rails.application.routes.draw do
  resources :usuarios, :tarefas
  get '/', to: "home#index"
  get '/login', to: "home#login"
  get '/sair', to: "home#sair"
  post '/checarLogin', to: "home#checarLogin"
end

app/models/tarefa.rb
class Tarefa < ActiveRecord::Base
  belongs_to :usuario
  validates_presence_of :texto
  validates_presence_of :data
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many :tarefas
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !session[:idUsuario] then
      redirect_to('/login')
    else
      @usuario = Usuario.find(session[:idUsuario])
      @tarefas = @usuario.tarefas
    end
  end

  def login
    @titulo = 'Login'
  end

  # POST /checarLogin
  def checarLogin

    if Usuario.find_by_login(params['login'])
      @usuario = Usuario.find_by_login(params['login'])
      if @usuario[:senha] == params['senha']
        session[:idUsuario] = @usuario.id
        session[:nome] = @usuario.nome
        redirect_to('/')
      else
        flash[:notice] =  ""
        redirect_to('/login')
      end
    else
      flash[:notice] =  ""
      redirect_to('/login')
    end
  end

  def sair
    session.delete(:idUsuario)
    session.delete(:nome)
    redirect_to('/')
  end
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: [:show, :edit, :update, :destroy]

  # GET /tarefas
  # GET /tarefas.json
  def index
    @tarefas = Tarefa.all
  end



  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully created.' }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1
  # PATCH/PUT /tarefas/1.json
  def update
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa.destroy
    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: 'Tarefa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarefa_params
      a = {}
      a['texto']=params['texto']
      a['data']=params['data']
      a['usuario_id']=params['id']
      return a
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end


  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuário criado com sucesso! faça o login.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario

      if params[:id].to_i != 0
        @usuario = Usuario.find(params[:id])
      else
        @usuario = Usuario.find_by_login(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      a = {}
      a['login']=params['login']
      a['senha']=params['senha']
      a['nome'] = params['nome']
      a['dataNasc'] = params['dataNasc']
      a['email'] = params['email']
      return a
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <h2>Bem Vindo a sua To Do List</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
    <div class="container-fluid">
      <div class="row">
        <%= form_tag({controller: 'tarefas', action: 'create'}, method: 'post') do%>
            <div class="form-group">
              <%= label_tag(:texto, 'Digite a sua tarefa') %>
              <%= text_field_tag(:texto, value = nil, options = {'class' =>  'form-control'}) %>
            </div>
            <div class="form-group">
              <%= label_tag(:data, 'Data da Tarefa') %>
              <%= text_field_tag(:data, value = nil, options = {'class' =>  'form-control', 'type' => 'date'}) %>
            </div>
            <input name="id" type="hidden" value="<%= session[:idUsuario]%>">
            <div class="actions">
            </div>
            <input type="submit" value="Criar Tarefa">
            </div>

        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="container-fluid">
      <% @tarefas.each do |tarefa| %>
      <div class="row">
        <div class="col-md-6 text-justify">
          <div class="alert alert-success" role="alert"><%= tarefa.texto %></div>
        </div>
        <div class="col-md-3">
          <button class="btn btn-lg btn-block btn-primary"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Alterar</button>
        </div>
        <div class="col-md-3">
          <button class="btn btn-lg btn-block btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Excluir</button>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/login.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>Acesse sua lista</h1>
    </div>
  </div>
</div>
<% if flash[:notice] %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="alert alert-danger" role="alert"><strong>Oh não :( </strong> Usuário ou Senha incorretos</div>
  </div>
</div>
<% end %>
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <%= form_tag(controller: 'home', action: 'checarLogin', method: 'post') do%>
      <div class="form-group">
        <label for="login">Login</label>
        <input class="form-control" type="text" name="login" id="login">
      </div>
      <div class="form-group">
        <label for="senha">Senha</label>
        <input class="form-control" type="password" name="senha" id="senha">
      </div>
      <button type="submit" class="btn btn-lg btn-block btn-primary">Entrar</button>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-offset-4 col-md-4 text-center">
    <h4><%= link_to("Ou cadastre-se aqui!", "usuarios/new") %></h4>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="toDoList">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if@titulo  %>
      <title><%= @titulo %> - To Do List</title>
  <% else %>
     <title>To Do List</title>
  <% end %>

  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.16/angular.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Bootstrap -->

</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">To Do List<% if session[:idUsuario] then %> - Olá, <%= session[:nome] %> <% end %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if session[:idUsuario] then %>
            <li><a href="/usuarios/<%= session[:idUsuario] %>/edit">Conta</a></li>
            <li><a href="/sair">Sair</a></li>
        <% else %>
            <li><a href="/usuarios/new">Cadastre-se</a></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container-fluid">
<%= yield %>

</div>
</body>
</html>

app/views/tarefas/_form.html.erb
<%= form_for(@tarefa) do |f| %>
  <% if @tarefa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
      <% @tarefa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tarefas/edit.html.erb
<h1>Editing Tarefa</h1>

<%= render 'form' %>

<%= link_to 'Show', @tarefa %> |
<%= link_to 'Back', tarefas_path %>

app/views/tarefas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tarefas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tarefas.each do |tarefa| %>
      <tr>
        <td><%= link_to 'Show', tarefa %></td>
        <td><%= link_to 'Edit', edit_tarefa_path(tarefa) %></td>
        <td><%= link_to 'Destroy', tarefa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tarefa', new_tarefa_path %>

app/views/tarefas/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>Cadastro de Tarefas</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_tag({controller: 'tarefas', action: 'create'}, method: 'post') do%>
        <div class="form-group">
          <%= label_tag(:texto, 'Digite a sua tarefa') %>
          <%= text_field_tag(:texto, value = nil, options = {'class' =>  'form-control'}) %>
        </div>
        <div class="form-group">
          <%= label_tag(:data, 'Data da Tarefa') %>
          <%= text_field_tag(:data, value = nil, options = {'class' =>  'form-control', 'type' => 'date'}) %>
        </div>
        <input name="id" type="hidden" value="<%= session[:idUsuario]%>">
        <div class="actions">
        </div>
        <%= render 'form' %>
        </div>

    <% end %>
    </div>
</div>



<%= link_to 'Back', tarefas_path %>

app/views/tarefas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tarefa_path(@tarefa) %> |
<%= link_to 'Back', tarefas_path %>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editar dados da Conta</h1>


<form>
<input type="text" class="form-control" value="<%=  @usuario.nome %>">
</form>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome        %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1>Cadastro</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_tag({controller: 'usuarios', action: 'create'}, method: 'post') do%>
        <div class="form-group">
          <%= label_tag(:login, 'Login') %>
          <%= text_field_tag(:login, value = nil, options = {'class' =>  'form-control'}) %>
        </div>
        <div class="form-group">
          <%= label_tag(:senha, 'Senha') %>
          <%= text_field_tag(:senha, value = nil, options = {'class' =>  'form-control', 'type' => 'password'}) %>
        </div>
        <div class="form-group">
          <%= label_tag(:confirmaSenha, 'Confirme a Senha') %>
          <%= text_field_tag(:confirmaSenha, value = nil, options = {'class' =>  'form-control', 'type' => 'password'}) %>
        </div>
        <div class="form-group">
          <%= label_tag(:nome, 'Nome Completo') %>
          <%= text_field_tag(:nome, value = nil, options = {'class' =>  'form-control'}) %>
        </div>
        <div class="form-group">
          <%= label_tag(:dataNasc, 'Data de Nascimento') %>
          <%= text_field_tag(:dataNasc, value = nil, options = {'class' =>  'form-control', 'type' => 'date'}) %>
        </div>
        <div class="form-group">
          <%= label_tag(:email, 'Email') %>
          <%= text_field_tag(:email, value = nil, options = {'class' =>  'form-control', 'type' => 'email'}) %>
        </div>
        <div class="actions">
        </div>
        <%= submit_tag %>
        </div>

    <% end %>
  </div>
</div>


<%= link_to 'Voltar', '/' %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>